### ISSUE TITLE
Метод public int sumGenre(String genre) не суммирует время игр

### ISSUE THREAD

**Issue by thatmarcello** [Debellaresupe/GraduationProject#1]
# Описание
Метод public int sumGenre(String genre) не суммирует время игр

# Локаци дефекта
https://github.com/Debellaresupe/GraduationProject/blob/6092bb1b5ca4c51d98f86329d856afde1ba8cb32/src/main/java/ru/netology/Player.java#L45-L56

# Шаги воспроизведения
1.Запустить [тест](https://github.com/Debellaresupe/GraduationProject/blob/6092bb1b5ca4c51d98f86329d856afde1ba8cb32/src/test/java/ru/netology/PlayerTest.java#L8-L20)

# Скриншот
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/103608366/187189140-4cf20747-850d-4059-bcec-90fdc9873863.png">

# Окружение
# Окружение 
* Операционная система: MacOS 12.5
* IDE: IntelliJ IDEA 2022.1.2 (Community Edition) 
* JAVA: OpenJDK 11.0.15

**Comment by Debellaresupe** [comment]
Внес исправления в код
![image](https://user-images.githubusercontent.com/86720647/187204313-4169f134-8f6d-4fef-9465-c56b9a2d35d2.png)
