### ISSUE TITLE
Метод containsGame в классе GameStore не находит игру и возвращает значение false

### ISSUE THREAD

**Issue by Debellaresupe** [Debellaresupe/GraduationProject#2]
# **Описание**
Метод containsGame в классе GameStore не находит игру и возвращает значение false, после добавления игры в Store

 # **Локация дефекта**
https://github.com/Debellaresupe/GraduationProject/blob/6092bb1b5ca4c51d98f86329d856afde1ba8cb32/src/main/java/ru/netology/GameStore.java#L32-L38
 
 # **Шаги воспроизведения**
1. Открыть [код программы/ветка gamestore](https://github.com/Debellaresupe/GraduationProject/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA
 2. Запустить тест shouldAddGame из класса [GameStoreTest](https://github.com/Debellaresupe/GraduationProject/blob/main/src/test/java/ru/netology/GameStoreTest.java)
3. Проверить вывод на консоли
 
 _Ожидаемый результат_: Тест проходит. Результат теста true _Фактический результат_: Тест не проходит. Результат теста false. Сообщение в консоли о несоответствии ожидаемого результата фактическому
 
 # **Скриншот**
![image](https://user-images.githubusercontent.com/86720647/187188928-2d422c74-3cb8-4e5c-9567-0cc78d16d39c.png)
 
 # **Окружение**
* Операционная система: Windows 10
* IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
* JAVA: OpenJDK 11.0.15

**Comment by thatmarcello** [comment]
* Исправлен код в issue #2
<img width="494" alt="image" src="https://user-images.githubusercontent.com/103608366/187193263-0b5b92ce-2bc6-4a7b-bc3e-9d52061eccf0.png">
