### ISSUE TITLE
Метод public int play не выдает RunTimeExeption.

### ISSUE THREAD

**Issue by thatmarcello** [Debellaresupe/GraduationProject#3]
# Вызов к неустановленной игре не выдает RunTimeExeption в методе public int play(Game game, int hours)

# Локация дефекта:
https://github.com/Debellaresupe/GraduationProject/blob/6092bb1b5ca4c51d98f86329d856afde1ba8cb32/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения:
1. Запустить [тест](https://github.com/Romagor/Team-project/blob/4380ab7686dcbffdb8ba5f6ef0baf6684f781894/src/test/java/ru/netology/PlayerTest.java#L65-L79)
1. Посмотреть результат в консоли

*Ожидаемый результат: * Выводится ошибка "RuntimeException"
*Фактический результат: *org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/103608366/187200369-336963b9-4362-4391-9880-6da5752f7c0d.png">

# Окружение 
* Операционная система: macOS 12.5
* IDE: IntelliJ IDEA 2022.1.2 (Community Edition) 
* JAVA: OpenJDK 11.0.15

**Comment by Debellaresupe** [comment]
Внес исправления в код
![image](https://user-images.githubusercontent.com/86720647/187204509-0874a937-3b40-4080-b0f6-be17bffd262c.png)
