### ISSUE TITLE
Метод getMostPlayer, в классе Gamestore, не принимает значение времени равное 1

### ISSUE THREAD

**Issue by Debellaresupe** [Debellaresupe/GraduationProject#4]
# **Описание**
В классе Gamestore метод getMostPlayer, не принимает значение времени равное 1

# **Локализация**
https://github.com/Debellaresupe/GraduationProject/blob/12db5448638225783c3cf50aad95213588df70ae/src/main/java/ru/netology/GameStore.java#L58-L69
 
# **Шаги воспроизведения**
1. Открыть [код программы/ветку gamestore](https://github.com/Debellaresupe/GraduationProject/blob/player/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2. Запустить тест shouldGetMostPlayerEquallyOne
3. Проверить вывод в консоли

**Ожидаемый результат**: Тест проходит. Результат теста - метод getMostPlayer вернул значение имени игрока "Пётр", время добавилось
**Фактический результат**: Тест не проходит. Сообщение в консоли о несоответствии ожидаемого результата фактическому

# **Скриншот**
![image](https://user-images.githubusercontent.com/86720647/187202260-1aa434a6-7428-40dd-bb95-f5795b21aaa0.png)

# **Окружение**
* Операционная система: Windows 10
* IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
* JAVA: OpenJDK 11.0.15

**Comment by thatmarcello** [comment]
Код в методе getMostPlayer исправлен
<img width="467" alt="image" src="https://user-images.githubusercontent.com/103608366/187205134-21d51f10-7bec-4d50-bb3a-0159a701888e.png">
