### ISSUE TITLE
Метод getSumPlayedTime в классе GameStore не возвращает сумму времени всех игроков

### ISSUE THREAD

**Issue by Debellaresupe** [Debellaresupe/GraduationProject#5]
# **Описание**
Метод getSumPlayedTime в классе GameStore не возвращает сумму времени всех игроков, а возвращает ноль

# **Локализация дефекта**
https://github.com/Debellaresupe/GraduationProject/blob/6092bb1b5ca4c51d98f86329d856afde1ba8cb32/src/main/java/ru/netology/GameStore.java#L71-L78

# **Шаги воспроизведения**
1. Открыть [код программы/ветку player](https://github.com/Debellaresupe/GraduationProject/blob/player/src/main/java/ru/netology/GameStore.java)
2. Запустить тест shouldGetSumPlayedTime в классе GameStoreTest
3. Проверить вывод на консоли

**Ожидаемый результат**: Тест проходит. Время суммировалось, метод getSumPlayedTime вернул верное значение - 10 **Фактический результат**: Тест не проходит. Метод getSumPlayedTime возвращает неверное значение - 0

# **Скриншот**
![image](https://user-images.githubusercontent.com/86720647/187207023-6c9972e6-1a3d-47fa-bdfd-057b34bde1d9.png)

# **Окружение**
* Операционная система: Windows 10
* IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
* JAVA: OpenJDK 11.0.15

**Comment by thatmarcello** [comment]
Метод дописан код исправлен
<img width="683" alt="image" src="https://user-images.githubusercontent.com/103608366/187214289-47a66d24-3497-4b6d-8d65-db7b40789f6d.png">
