### ISSUE TITLE
К коллекции playedTime нет доступа

### ISSUE THREAD

**Issue by thatmarcello** [Debellaresupe/GraduationProject#8]
3 Описание.

Невозможно обратиться к коллекции playedTime в классе Player.

# Локация дефекта.

https://github.com/Debellaresupe/GraduationProject/blob/6092bb1b5ca4c51d98f86329d856afde1ba8cb32/src/main/java/ru/netology/Player.java#L12

# Шаги воспроизведения

Открыть код программы
Запустить [тест](https://github.com/Debellaresupe/GraduationProject/blob/f4cf5aa04820338b8b6d2d473aff4d4ddf1a3d84/src/test/java/ru/netology/PlayerTest.java#L60-L71)
Посмотреть на вывод в консоли.

**Ожидаемый результат:** Тест проходит, ошибок нет.
**Фактический результат:** Тест не проходит. Сообщение в консоли: java: playedTime has private access in ru.netology.Player.

# Скриншот
<img width="740" alt="image" src="https://user-images.githubusercontent.com/103608366/187217445-830ccde6-aa61-4f82-9408-3433ffb8a7af.png">

**Comment by Debellaresupe** [comment]
Поменял модификатор доступа
![image](https://user-images.githubusercontent.com/86720647/187218146-e19dbd41-1485-4cb7-8448-7b70bb9316f4.png)
